wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708092474.585492
    t:
      1:
      - 1
      - 41
      - 55
      - 82
      2:
      - 1
      - 41
      - 55
      - 82
      3:
      - 13
      - 23
      - 35
      4: 3.8.18
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
